// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "45444c7a-9c6a-42ed-8c94-413e098a2b3d";

const char SSID[]               = "Wack House";    // Network SSID (name)
const char PASS[]               = "justice69";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "mIB9Ezs8tfWtqe8Mx2qhQgYxT";    // Secret device password

void onStatusMessageChange();
void onCloudMonitoringChange();
void onIsMonitoringChange();
void onCloudRestartChange();

String statusMessage;
float temperature;
bool cloudMonitoring;
bool isMonitoring;
bool cloudRestart;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(statusMessage, READWRITE, ON_CHANGE, onStatusMessageChange);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cloudMonitoring, READWRITE, ON_CHANGE, onCloudMonitoringChange);
  ArduinoCloud.addProperty(isMonitoring, READWRITE, ON_CHANGE, onIsMonitoringChange);
  ArduinoCloud.addProperty(cloudRestart, READWRITE, ON_CHANGE, onCloudRestartChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
